"""Create messages table

Revision ID: b196c86025f1
Revises: d44bb524ed1f
Create Date: 2024-09-04 15:42:56.705565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b196c86025f1'
down_revision = 'd44bb524ed1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
